proxy:
  port: 80
  container-wait-time: 30000
  authentication: none
  admin-groups: admins
  docker:
      internal-networking: true
  specs:
  - id: PIPprofileR
    description: PIPprofileR
    container-cmd: ["R", "-e", "PIPprofileR::shiny_application(port = 3838, host = '0.0.0.0')"]
    container-image: tdenecker/pip-profiler
    container-network: sp-network
logging:
  file:
    shinyproxy.log